[package]
name = "memory-leak"
version = "0.1.0"
authors = ["James <jracollins@gmail.com>"]
edition = "2018"

[build-dependencies]

[dependencies]
fastrand = "1.5.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
